In [1]:
import numpy as np 
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

In [3]:
df = pd.read_csv(r'C:\Users\lenovo\Desktop\vishakha\amazon_reviews_1.csv')
df.head()

Unnamed: 0 marketplace  customer_id       review_id  product_id  \
0       35311          UK      4652511  R2PF9XCB2AOY7C  B00MNYTWMI   
1       44590          UK      8778070  R2OVRHVTCC7U18  B00I8Q77Y0   
2       90295          UK      8476187   RRPSNSVU2RNE4  B008PEHK6U   
3       38798          UK      4329864  R1WK44Y81XH276  B00NWLIW0E   
4       43364          UK      8080547  R2UL591NPU40SN  B00HRC40T6   

   product_parent                                      product_title  \
0       174964168  Midnight Castle – A Free Hidden Object Mystery...   
1       370420344                     Flappy Wings (not Flappy Bird)   
2       173475712                                 Man of Steel [DVD]   
3        13526192                                     Goat Simulator   
4       887316735                                       Shadow Blade   

  product_category  star_rating  helpful_votes  total_votes vine  \
0      Mobile_Apps            5              0            1    N   
1      Mobile_Apps            2              1            2    N   
2        Video DVD            3              1            5    N   
3      Mobile_Apps            1              3            5    N   
4      Mobile_Apps            1              0            0    N   

  verified_purchase review_date  \
0                 Y  2014-09-16   
1                 Y  2014-02-16   
2                 N  2013-12-28   
3                 N  2014-12-26   
4                 Y  2015-06-29   

                                              review  review_category  
0  Addictive game Very good game, the graphics ar...                1  
1  Where to start? I came on here because I wante...                0  
2  Really Disappointed in this Film I have to say...                0  
3  Rubbish game When I tried to open it, it said ...                0  
4                                   One Star Come on                0

In [4]:
df.shape

(10000, 16)

In [5]:
# Data preparation 
df.dropna(inplace = True)

In [6]:
x = df['review']
y = df['review_category']

In [7]:
import re

In [8]:
# Text cleaning

x_new = []

for review in x:
    review = re.sub('[^a-zA-Z ]', '', review) # punctuation, special characters, number removal 
    review = review.lower()                  # Convert all characters to lowercase
    x_new.append(review)                     # finally adding it to our new list
    

In [9]:
'Very bad $Service !!!! you can go to h%%l I was waiting for the deliver for past 23 days '

'Very bad $Service !!!! you can go to h%%l I was waiting for the deliver for past 23 days '

In [10]:
x_new[45] 

'embarrassing i dont know which actor made me cringe more nicholson and keatons characters flounce around like teens in heat hysterical not funnily soand gruesomely selfindulgent by turns not remotely believable or sympathetic long before the midway point i ceased to give a damn about them or their lovelives and poor keanu is a mere cipher in this sorry mess he looks bemused most of the time   as in what the hell am i doing in this kind of bemused barely a decent laugh in it either actually two stars is probably pretty generous'

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x_new, y, test_size = 0.2, random_state=234)

In [12]:
# Bag of Words
vector = CountVectorizer(stop_words = 'english').fit(x_train)

In [13]:
vector.get_feature_names()

['aaa',
 'aaaaaapredators',
 'aagh',
 'aanrader',
 'aardman',
 'aare',
 'aaron',
 'aat',
 'ab',
 'abacab',
 'aback',
 'abandon',
 'abandoned',
 'abating',
 'abba',
 'abbado',
 'abbasound',
 'abbatoir',
 'abbey',
 'abbott',
 'abby',
 'abcs',
 'abdi',
 'abduction',
 'abel',
 'aberation',
 'abercrombie',
 'abercrombies',
 'abhored',
 'abilities',
 'ability',
 'abilty',
 'abit',
 'abject',
 'able',
 'ablums',
 'ably',
 'abnormality',
 'abnoxious',
 'aboard',
 'abode',
 'abolish',
 'abominable',
 'abomination',
 'abominationthe',
 'abound',
 'abousoloutly',
 'aboutas',
 'aboutbr',
 'abouthow',
 'aboutit',
 'aboutnot',
 'aboutummm',
 'abovebr',
 'aboveim',
 'aboveunlikely',
 'abr',
 'abrams',
 'abrasive',
 'abridged',
 'abriged',
 'abroad',
 'abrubtly',
 'abrupt',
 'abruptly',
 'abrutly',
 'abs',
 'absaloutly',
 'abseil',
 'absence',
 'absent',
 'absolotely',
 'absoloute',
 'absoloutely',
 'absolute',
 'absolutely',
 'absolution',
 'absolutiuon',
 'absolutley',
 'absolutly',
 'absorb',
 'abs

In [24]:
len(vector.get_feature_names())

25111

In [14]:
x_transform = vector.transform(x_train)
x_transform

<7999x25111 sparse matrix of type '<class 'numpy.int64'>'
	with 165334 stored elements in Compressed Sparse Row format>

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
model_lr = LogisticRegression()
model_lr.fit(x_transform, y_train)

C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [17]:
predictions = model_lr.predict(vector.transform(x_test))
print(classification_report(predictions, y_test))

              precision    recall  f1-score   support

           0       0.81      0.84      0.83       954
           1       0.85      0.82      0.84      1046

    accuracy                           0.83      2000
   macro avg       0.83      0.83      0.83      2000
weighted avg       0.83      0.83      0.83      2000



In [18]:
r1 = 'The product was very bad'
predict_r1 = model_lr.predict(vector.transform([r1]))
predict_r1

array([0], dtype=int64)

In [19]:
# Tfidf - Term Frequency Inverse document Frequency
vector_tf = TfidfVectorizer(stop_words='english').fit(x_train)
xtf_transform = vector_tf.transform(x_train)

In [20]:
model_lr_tf = LogisticRegression()
model_lr_tf.fit(xtf_transform, y_train)

LogisticRegression()

In [21]:
prediction_tf = model_lr_tf.predict(vector_tf.transform(x_test))
print(classification_report(prediction_tf, y_test))

              precision    recall  f1-score   support

           0       0.87      0.82      0.85      1059
           1       0.81      0.87      0.84       941

    accuracy                           0.84      2000
   macro avg       0.84      0.84      0.84      2000
weighted avg       0.84      0.84      0.84      2000



In [22]:
r2 = 'the product was found in bad condition'
prediction_tf_r2 = model_lr_tf.predict(vector_tf.transform([r2]))
prediction_tf_r2

array([0], dtype=int64)

In [23]:
r2 = 'the product was not good'
prediction_tf_r2 = model_lr_tf.predict(vector_tf.transform([r2]))
prediction_tf_r2

array([1], dtype=int64)